
[functions]
  directory = "my_functions"
# it shows content from proxysample page instead of the contents inside sample page
[[redirects]]
  from = "/sample"
  to = "/proxysample"
  status = 200
  force = true


